manifest:

  projects:
    - name: zephyr
      url: https://github.com/zephyrproject-rtos/zephyr
      revision: main
      path: zephyr
      west-commands: scripts/west-commands.yml
      import:
        name-allowlist:
          - cmsis
          - hal_stm32
          - picolibc

    - name: libros2-zephyr
      url: https://github.com/yashi/libros2-zephyr
      revision: main
      path: libros2-zephyr
      import:
        path-prefix: modules/ros2

  self:
    path: micro-ros-zephyr-demo
